---
functional:
#РЕГИСТРАЦИЯ
  - Пользователь может зарегистрироваться в системе, указав ник, email, пароль и его подтверждение на странице регистрации
  - Пользователь может зарегистрироваться в системе с использованием внешнего сервиса GitHub
  - Пользователь может зарегистрироваться в системе с использованием внешнего сервиса Discord
# ВХОД В СИСТЕМУ
  - Пользователь может войти в систему, указав email и пароль, заданные при регистрации
  - Пользователь может войти в систему с использованием внешнего сервиса GitHub
  - Пользователь может войти в систему с использованием внешнего сервиса Discord
# ВОССТАНОВЛЕНИЕ ПАРОЛЯ
  - Пользователь может запросить ссылку для смены пароля на почту, указанную при регистрации
  - Пользователь может сменить пароль по ссылке в полученном письме
  - Пользователь может войти в систему по измененному паролю
# СОЗДАНИЕ ИГРЫ
  - При нажатии на кнопку "Create a game" должно появляться модальное окно "Create a game"\
  - Пользователь может создать игру типа "With other user" по кнопке "Create battle" в модальном окне "Create a game"
  - При создании игры пользователь может отфильтровать список задач по уровню сложности
  - При создании игры пользователь может отфильтровать список задач по тегам
  - При создании игры в модальном окне "Create a game" пользователь может задать контроль времени
  - При создании игры в модальном окне "Create a game" пользователь может выбрать задачу из списка доступных в секции Choose task by name or tags
  - Параметры созданной игры должны соответствовать параметрам, указанным при её создании в окне Create a game
  - При клике на иконку Send fight invite в окне чата главной страницы открывается модальное окно Send battle invite для выбора оппонента
  - При выборе оппонента в окне Send battle invite  открывается модальное окно "Create a game"
  - После выбора оппонента в окне Send battle invite, в открывающемся окне Create a game тип игры автоматически устанавливается на "With a friend"
  - После выбора оппонента в окне Send battle invite, в открывающемся окне Create a game ник оппонента устанавливается автоматически
  - Кнопка Create invite в окне Create a game неактивна, если не выбран ник пользователя
  - Пользователь может отправить другому пользователю приглашение на битву по кнопке "Create invite"
  - Пользователь видит приглашения на битву, которые ему присылают другие пользователи
  - Пользователь видит приглашения на битву, которые ему присылают другие пользователи
  - Пользователь может вступить в битву по приглашению от другого пользователя
# ПОДКЛЮЧЕНИЕ К ИГРЕ
  - Пользователь, создавший сражение типа "With other user", не может присоединиться к нему, пока не присоединится его оппонент
  - Пользователь получает ссылку на созданное им сражение типа "With other user" по кнопке Copy link в таблице вкладки LOBBY на главной странице 
  - Пользователь, создавший сражение типа  "With other user" может отменить его, пока к нему не подключился оппонент
  - Пользователь может вступить в сражение типа "With other user" по ссылке
  - Пользователь может вступить в сражение типа "With other user" по кнопке Fight в таблице вкладки LOBBY на главной странице
  - Таймер сражения типа  "With other user"  запускается, когда в сражение вступает оппонент пользователя.
# ИГРОВОЙ ПРОЦЕСС
  - Победа присуждается пользователю, если его оппонент добровольно сдался
  - Победа присуждается игроку, чьё решение первым удачно проходит все тесты задачи
  - Код в редакторе оппонента пользователя обновляется в реальном времени
  - Код в редакторе оппонента пользователя обновляется в реальном времени
  - Пользователь уведомляется по результату выполнения тестов решения оппонента
  - Пользователь может посмотреть вывод тестов оппонента во вкладке в правом нижнем окне страницы сражения
  - Пользователи могут следить за ходом любой активной игры
  - Запись игры можно открыть по кнопке Open History в окне чата сражения
  - Пользователь может выйти со страницы сражения на главную страницу приложения по кнопке Back to home в окне чата сражения
  - Пользователь может вернутся в активное сражение по кнопке Continue в таблице вкладки LOBBY на главной странице
  - Победитель может предложить проигравшему реванш по кнопке Rematch в окне чата битвы
  - Игрок может согласится на реванш по кнопке Accept в окне чата битвы
  - Игрок может отказаться от реванша по кнопке Decline в окне чата битвы
  - Проигравший может предложить проигравшему реванш по кнопке Rematch в окне чата битвы
  - Если вдруг один из игроков вылетел из игры, второй может продолжать играть
  - Выигравший пользователь сражения получает уведомление о победе в модальном окне
  - Модальное окно, уведомляющее о победе можно закрыть по кнопке закрытия
  - Проигравший  пользователь получает уведомление о поражении в модальном окне
  - Модальное окно, уведомляющее о поражении, можно закрыть по кнопке закрытия в модальном окне
  - Описание постановки задачи в верхнем левом окне страницы сражения можно развернуть в модальное окно по кнопке Expand
  - Пользователь может сменить язык описания задачи в выпадающем списке EN/RU в верхнем левом окне страницы сражения
  - Пользователь может посмотреть результат прохождения тестов написанного им кода во вкладке OUTPUT в левом верхнем окне страницы сражения
  - Пользователь видит таймер, показывающий оставшееся до конца сражения время
  - Если сражение завершается по истечению таймера, то оба противника считаются проигравшими
  - Пользователь может выбрать один из доступных для решения задачи ЯП из выпадающего списка в окне своего редактора
  - Пользователь может активировать темную тему обоих редакторов кода по кнопке Dark/Light в окне своего редактора
  - Пользователь может добровольно сдаться по кнопке Give Up в окне своего редактора кода
  - Пользователь может очистить написанный им код решения по кнопке Reset Solution в окне своего редактора
  - Пользователь может запустить тест написанного им кода по кнопке Run в окне своего редактора.
  - Пользователь может переключиться на Vim модель управления редактором кода в окне своего редактора по кнопке Vim
  - Пользователь может запускать проигрывание истории написания решений соперников по кнопке Play/Pause на панеле управления просмотром
  - Пользователь может ставить на паузу проигрывание истории написания решений соперников по кнопке Play/Pause на панели управления просмотром
  - Пользователь может перематывать проигрывание истории написания решений с помощью трекера прогресса на панеле управления просмотром
  - Пользователь может ускорить воспроизведение истории написания решений по кнопке  x2 в меню настроек панели управления просмотром
  - Пользователь может скопировать URL записи игры по кнопке в меню настроек панели управления просмотром
  - Пользователь может запускать тесты своих решений после собственного поражения в сражении
# ФУНКЦИОНАЛ НА ГЛАВНОЙ СТРАНИЦЕ
  - Кнопка уведомлений должна отображать сумму отправленных и полученных приглашений на сражения
  - В шапке интерфейса приложения должно отображаться количество авторизованных на текущий момент пользователей
  - Пользователь может перейти на страницу рейтинга по ссылке на главной странице под элементом LEADERBOARD
  - Пользователь может переключаться между различными периодами составления рейтинга элемента LEADERBOARD, неделя, месяц, всё время
# ВЫПАДАЮЩЕЕ МЕНЮ ПОЛЬЗОВАТЕЛЯ
  - Пользователь может перейти на страницу своего профиля по элементу My Profile в списке выпадающего меню пользователя
  - Пользователь может перейти на страницу персональных настроек по элементу Settings в списке выпадающего меню пользователя
  - Пользователь может перейти на страницу пользовательских рейтингов по элементу User rating в списке выпадающего меню пользователя
  - Пользователь может перейти на страницу со списком задач по элементу Tasks в списке выпадающего меню пользователя
  - Пользователь может перейти на страницу с турнирами по элементу Tournaments в списке выпадающего меню пользователя
  - Пользователь может перейти на страницу с репозиторием проекта на GitHub по элементу SourceCode в списке выпадающего меню пользователя
  - Пользователь может перейти на страницу Hexlet по элементу Hexlet в списке выпадающего меню пользователя
  - Пользователь может перейти на страницу сообщества Hexlet в Telegram по элементу Tg#codebattle в списке выпадающего меню пользователя
  - Пользователь может завершить сессию по элементу Sign Out в списке выпадающего меню пользователя
  - Пользователю может получить приглашение на вступление в сообщество CodeBattle на платформе Discord
# ПЕРСОНАЛЬНЫЕ НАСТРОЙКИ
  - На странице настроек пользователь может изменить своё имя, отображаемое в приложении
  - Имя пользователя после изменения в персональных настройках должно также в измененном виде отображаться в других частях приложения
  - На странице настроек пользователь может изменить ЯП по умолчанию
  - На странице настроек пользователь может задать имя клана
  - На странице настроек пользователь может выбрать вариант озвучания интерфейса из списка предложенных
  - При изменении варианта озвучания интерфейса проигрывается соответствующий звуковой отрывок, кроме варианта Silent
  - На странице настроек пользователь может регулировать уровень громкости интерфейса ползунком
  - На странице настроек пользователь может задать желаемый уровень громкости озвучания интерфейса
# ТРЕБОВАНИЯ К ПАНЕЛИ СТАТУСОВ ПОЛЬЗОВАТЕЛЕЙ
  - Пользователи с одинаковыми статусами группируются при отображении в панели статусов
  - Пользователи, наблюдающие за активной игрой на странице сражения, отображаются в категории Watching
  - Пользователи, просматривающие статусы завершенных игр, отображаются в категории Watching 
  - Любой пользователь, который является игроком, находящимся на странице сражения, отображается в категории Playing
  - При клике на кнопку отправки приватного сообщения в панели статусов пользователей открывается модальное окно со списком доступных пользователей
  - В модальном окне отправки приватного сообщения пользователь может выбрать любого из доступных ему пользователей
  - Отображение сообщений из приватной комнаты дублируется в общую комнату для пользователей-участников этой приватной комнаты
  - Сообщения в приватной комнате могут читать только участники этой приватной комнаты
  - На странице профиля во вкладке завершенных игр можно посмотреть статус каждой игры по кнопке Show
  - Пользователь может посмотреть перечень идущих боёв на вкладке LOBBY на панели вкладок главной странице
# ТАБ-КОНТЕЙНЕР НА ГЛАВНОЙ СТРАНИЦЕ
  - Пользователь может посмотреть перечень боёв в статусе playing на вкладке LOBBY на панели вкладок главной странице
  - Пользователь может посмотреть перечень боёв с ботами, находящихся в режиме ожидания игроков, на главной странице
  - Пользователь может посмотреть перечень боёв типа "With other user", находящихся в режиме ожидания игроков
  - Пользователь может вступить в сражение, находящееся в режиме ожидания игроков, по кнопке Fight в колонке Actions таблицы вкладки LOBBY
  - Пользователь может просмотреть статус любого завершённого сражения по кнопкам Show вкладки HISTORY
# ТРЕБОВАНИЯ К ОКНУ ЧАТА НА ГЛАВНОЙ СТРАНИЦЕ
  - Пользователь может выбрать любую доступную ему комнату чата в выпадающем списке в окне чата
  - Каждый авторизованный пользователь может отправить сообщение в комнату чата General
  - Список доступных эмодзи открывается по иконке эмодзи в окне чата
  - Пользователь может отправлять любой эмодзи из списка доступных по иконке в окне чата
  - Окно чата должно поддерживать прокрутку для просмотра истории сообщений, если они не помещаются в окно чата
# ТРЕБОВАНИЯ К СТРАНИЦЕ РЕЙТИНГА
  - Пользователь может переключаться между таблицами пользовательского рейтинга 
  - Пользователь может найти другого зарегистрированного пользователя в таблице рейтинга по его Username
  - Пользователь может выставить чек-бокс With bots для включения ботов в таблицу пользовательского рейтинга
  - Пользователь может регулировать количество пользователей, выводимых при отображении страницы таблицы пользовательского рейтинга с помощью селектора количества элементов
  - Пользователь может отсортировать таблицу с рейтингом по возрастанию ранга пользователей 
  - Пользователь может отсортировать таблицу с рейтингом по возрастанию рейтинга пользователей
  - Пользователь может отсортировать таблицу с рейтингом по возрастанию количества завершенных сражений 
  - Пользователь может отсортировать таблицу с рейтингом по убыванию количества завершенных сражений 
  - Пользователь может отсортировать таблицу с рейтингом по убыванию даты регистрации пользователя
  - Пользователь может отсортировать таблицу с рейтингом возрастанию даты регистрации пользователя
  - Пользователь может переключиться на последнуюю страницу таблицы рейтинга кнопкой на панели пагинации
  - Пользователь может переключиться на первую страницу таблицы рейтинга кнопкой на панели пагинации
  - Пользователь может переключиться на страницу таблицы рейтинга вперед кнопкой на панели пагинации
  - Пользователь может переключиться на предыдущую страницу таблицы рейтинга кнопкой на панели пагинации
  - Пользователь може переключаться по номерам страниц таблицы рейтинга кнопками на панели пагинации
# ТРЕБОВАНИЯ К РАСЧЕТУ РЕЙТИНГА
  - ELO - рейтинг пользователя в поединке с ботом не меняется
  - ELO - рейтинг пользователя при проигрыше обоих игроков в поединке между людьми не меняется
  - ELO - рейтинг пользователя в поединке между людьми уменьшается на 10 единиц, если он добровольно сдается
  - ELO - рейтинг пользователя при победе в поединке между людьми увеличивается согласно методике расчета ELO - рейтинга
  - ELO-рейтинг пользователя при поражении в поединке между людьми уменьшается согласно методике расчета ELO - рейтинга
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь не может копипастить текст в окно редактора, если текст скопирован не из самого редактора
  - Пользователь не может скопировать текст из окна редактора оппонента
